server:
  port: 4041
spring:
  application:
    name: NTRS_CrudOps01
  datasource:
    dbcp2:
      driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:testdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
plan:
 module:
  messages:
   save-success: Travel Plan is saved with id value
   save-failure: Travel Plan is not saved with value
   find-by-id-failure: TravelPlan is not found
   update-success: Travel Plan is updated
   update-failure: Travel Plamn is not found for updation
   delete-success: Travel Plan is deleted
   delete-failure: Travel Plan is not found for deletion
   status-change-success: Travel Plan status is changed
   status-change-failure: Travel Plan is not found for status changes
   