server:
  port: 4041
spring:
  application:
    name: NTRS_CrudOps01
  datasource:
    dbcp2:
      driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:testdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
